### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by Rasbats** [leamas/shipdriver_pi#2]
Not happy with antora.yml in the root folder. Much prefer having antora.yml in a docs folder:

    ├── repo root folder
    │ ├── docs
    │           └── modules/ROOT
    │           ├── antora.yml

Slight change to the build.yml is needed
```
content:
  sources:
    - url: https://github.com/rgleason/ocpn-dev-manual.git
      branches: main   
      edit_url: false
    - url: https://github.com/leamas/ocpn-pi-docs.git
      branches: main
      edit_url: true
    - url: https://github.com/Rasbats/shipdriver_pi.git    
      branches: master
      start_path: docs
      edit_url: true 
```
This keeps the antora stuff together and allows the docs folder to be used for specific documentation stuff.
